import { exec } from "child_process";
import { NextResponse } from "next/server";
import { translatePromptToSql, generateAdvisorBriefing } from "../../../lib/llm";
import { AssignmentRow, AgentServerResponse } from "../../../types";

// Absolute path to the local coral binary on this Linux environment
const CORAL_BINARY_PATH = "/home/borngreat/.local/bin/coral";

function runCoralSql(sql: string): Promise<{ data: AssignmentRow[]; error?: string }> {
  return new Promise((resolve) => {
    // Sanitize query to prevent command injection (though it is generated by our system, always double secure)
    const sanitizedSql = sql.replace(/"/g, '\\"');
    const command = `"${CORAL_BINARY_PATH}" sql --format json "${sanitizedSql}"`;

    exec(command, (error, stdout, stderr) => {
      if (error) {
        console.error("Coral execution error:", error, stderr);
        return resolve({
          data: [],
          error: stderr || error.message || "Failed to execute Coral SQL query",
        });
      }

      try {
        const data = JSON.parse(stdout.trim()) as AssignmentRow[];
        resolve({ data });
      } catch (parseError) {
        console.error("Failed to parse Coral output:", parseError, stdout);
        resolve({
          data: [],
          error: "Failed to parse query results into JSON format",
        });
      }
    });
  });
}

export async function POST(request: Request) {
  try {
    const body = await request.json();
    const prompt = body.prompt || "";
    
    // Step 1: Translate NL prompt to standard SQL
    const sql = translatePromptToSql(prompt);

    // Step 2: Execute Coral SQL query on the seed local dataset
    const result = await runCoralSql(sql);

    if (result.error) {
      const errorResponse: AgentServerResponse = {
        sql,
        data: [],
        explanation: `### ❌ Query Execution Failure\nWe encountered an error while querying your local data source using Coral:\n\n\`\`\`\n${result.error}\n\`\`\``,
        error: result.error,
      };
      return NextResponse.json(errorResponse, { status: 500 });
    }

    // Step 3: Compile rich advisor explanation briefing
    const explanation = generateAdvisorBriefing(prompt, sql, result.data);

    // Step 4: Return strict AgentServerResponse
    const responseBody: AgentServerResponse = {
      sql,
      data: result.data,
      explanation,
    };

    return NextResponse.json(responseBody);
  } catch (err: unknown) {
    const errorMessage = err instanceof Error ? err.message : "Unknown internal server error";
    return NextResponse.json(
      {
        sql: "",
        data: [],
        explanation: "Internal agent server error occurred.",
        error: errorMessage,
      },
      { status: 500 }
    );
  }
}
